### ISSUE TITLE
animation speed broken in :host(.animate) 

### ISSUE THREAD

**Issue by dman777** [PolymerElements/paper-toolbar#54]
I am trying to change the animation speed. When adjusting the seconds, there is no effect:
1.0.4 version

``` css
   :host(.animate) {
      /* transition */
      transition: height 3s ease-in;
    }
```
